USE QLDonDatHang
GO
-- Tạo VIEW
-- 1. Liệt kê thông tin mã nhân viên, họ tên, tuổi, quê quán, số điện thoại, hệ số lương, lương (= HSL * 1500000)
CREATE VIEW CAU1
AS
SELECT
    NHANVIEN.MaNV,
    NHANVIEN.HoTen,
    DATEDIFF(YEAR, NHANVIEN.NgaySinh, GETDATE()) AS Tuoi,
    NHANVIEN.QueQuan,
    NHANVIEN.SDT,
    ISNULL(NHANVIEN.HSL, 0) AS HSL,
    (CAST(ISNULL(NHANVIEN.HSL, 0) AS float) * 1500000) AS Luong
FROM NHANVIEN;
GO

SELECT * FROM CAU1
GO
-- 2. Liệt kê các nhân viên cùng quê Hà Nội
CREATE VIEW CAU2
AS
SELECT * FROM NHANVIEN
WHERE NHANVIEN.QueQuan LIKE N'%Hà Nội'
GO 

SELECT * FROM CAU2
GO
-- 3. Liệt kê các mặt hàng của cùng nhà cung cấp có mã ‘0001’
CREATE VIEW CAU3
AS
SELECT 
	HANGHOA.MaHH,
	HANGHOA.TenHH,
	HANGHOA.GiaBan,
	HANGHOA.DacDiem
FROM HANGHOA
	INNER JOIN CT_PHIEUNHAP ON CT_PHIEUNHAP.MaHH = HANGHOA.MaHH
	INNER JOIN PHIEUNHAP ON PHIEUNHAP.MaPN = CT_PHIEUNHAP.MaPN
WHERE PHIEUNHAP.MaNCC = 0001
GO

SELECT * FROM CAU3
GO
-- 4. Tạo view doanh thu theo từng hóa đơn của tháng 11 năm 2021
CREATE VIEW CAU4
AS
SELECT
    CT_HOADON.MaHD,
    CAST(SUM(CT_HOADON.SL * HANGHOA.GiaBan) AS money) AS DOANHTHU
FROM CT_HOADON
    INNER JOIN HANGHOA ON HANGHOA.MaHH = CT_HOADON.MaHH
    INNER JOIN HOADON ON HOADON.MaHD = CT_HOADON.MaHD
WHERE YEAR(HOADON.NgayLap) = 2015 AND MONTH(HOADON.NgayLap) = 3
GROUP BY CT_HOADON.MaHD
GO

SELECT * FROM CAU4
GO
-- 5. Tạo view doanh thu theo mỗi khách hàng trong năm 2021
CREATE VIEW CAU5
AS
SELECT
	KHACHHANG.MaKH,
	CAST(SUM(CT_HOADON.SL * HANGHOA.GiaBan) AS money) AS DOANHTHU
FROM CT_HOADON
    INNER JOIN HANGHOA ON HANGHOA.MaHH = CT_HOADON.MaHH
    INNER JOIN HOADON ON HOADON.MaHD = CT_HOADON.MaHD
	INNER JOIN KHACHHANG ON KHACHHANG.MaKH = HOADON.MaKH
WHERE YEAR(HOADON.NgayLap) = 2015
GROUP BY KHACHHANG.MaKH
GO

SELECT * FROM CAU5
GO
-- 6. Tạo view liệt kê số tiền phải trả cho mỗi nhà cung cấp trong năm 2021
CREATE VIEW CAU6 
AS 
SELECT 
	PHIEUNHAP.MaNCC,
	CAST(SUM(CT_PHIEUNHAP.SL * CT_PHIEUNHAP.GiaMua) AS money) AS TIENCHI2021
FROM PHIEUNHAP
	INNER JOIN CT_PHIEUNHAP ON CT_PHIEUNHAP.MaPN = PHIEUNHAP.MaPN
WHERE YEAR(PHIEUNHAP.NgayLap) = 2015
GROUP BY PHIEUNHAP.MaNCC
GO 

SELECT * FROM CAU6
GO
-- 7. Tạo view số lượng nhập và bán ứng với mỗi sản phẩm trong năm 2021
CREATE VIEW CAU7
AS
SELECT
	NHAPHANG.MAHANG,
	NHAPHANG.SLNHAP,
	BANHANG.SLBAN
FROM (
	SELECT
		CT_PHIEUNHAP.MaHH AS MAHANG,
		SUM(CT_PHIEUNHAP.SL) AS SLNHAP
	FROM CT_PHIEUNHAP
		INNER JOIN PHIEUNHAP ON PHIEUNHAP.MaPN = CT_PHIEUNHAP.MaPN
	WHERE YEAR(PHIEUNHAP.NgayLap) = 2015
	GROUP BY CT_PHIEUNHAP.MaHH
	) AS NHAPHANG
	INNER JOIN 
	(
	SELECT
		CT_HOADON.MaHH AS MAHANG,
		SUM(CT_HOADON.SL) AS SLBAN
	FROM CT_HOADON
		INNER JOIN HOADON ON HOADON.MaHD = CT_HOADON.MaHD
	WHERE YEAR(HOADON.NgayLap) = 2015
	GROUP BY CT_HOADON.MaHH
	) AS BANHANG ON BANHANG.MAHANG = NHAPHANG.MAHANG
GO

SELECT * FROM CAU7
GO
/* ____________________________________________________________________________ */
-- Tạo PROC
-- 1. Cho biết tổng số tiền của một hóa đơn nào đó theo mã hóa đơn
CREATE PROCEDURE CAU1_PROC
(
	@MAHD NVARCHAR(20),
	@TONGTIEN MONEY OUTPUT
)
AS
BEGIN
	SELECT
		@TONGTIEN = SUM(CT_HOADON.SL * HANGHOA.GiaBan)
	FROM CT_HOADON
		INNER JOIN HANGHOA ON HANGHOA.MaHH = CT_HOADON.MaHH	
	WHERE CT_HOADON.MaHD = @MAHD
END
GO

-- Chạy test
DECLARE @TONG MONEY
EXEC CAU1_PROC '0016', @TONG OUTPUT
PRINT N'TỔNG TIỀN CỦA MÃ HÓA ĐƠN LÀ: ' + CONVERT(NVARCHAR,@TONG)
GO

-- 2. Cho biết tổng số hóa đơn đã lập được trong một tháng của một năm nào đó
CREATE PROCEDURE CAU2_PROC
(
	@NAM INT,
	@THANG INT,
	@TONGHD INT OUTPUT	
)
AS
BEGIN
	SELECT
		@TONGHD = COUNT(HOADON.MaHD)
	FROM HOADON
	WHERE YEAR(HOADON.NgayLap) = @NAM AND MONTH(HOADON.NgayLap) = @THANG
END
GO 

-- Chạy test
DECLARE @TONG INT
EXEC CAU2_PROC '2015', '3', @TONG OUTPUT
PRINT N'TỔNG HD: ' + CONVERT(NVARCHAR,@TONG)
GO

-- 3. Cho biết tổng số hóa đơn đã lập và tổng doanh thu đã bán hàng của một nhân viên trong một năm nào đó dựa vào mã nhân viên
CREATE PROCEDURE CAU3_PROC
(
	@MANV NVARCHAR(20),
	@NAM INT,
	@TONGHD INT OUTPUT,
	@TONGDOANHTHU MONEY OUTPUT
)
AS
BEGIN
	SELECT
		@TONGHD = COUNT(DISTINCT HOADON.MaHD),
		@TONGDOANHTHU = SUM(CT_HOADON.SL * HANGHOA.GiaBan) 
	FROM HOADON
		INNER JOIN CT_HOADON ON CT_HOADON.MaHD = HOADON.MaHD
		INNER JOIN HANGHOA ON HANGHOA.MaHH = CT_HOADON.MaHH
	WHERE HOADON.MaNV = @MANV AND YEAR(HOADON.NgayLap) = @NAM
END
GO

-- Chạy test
DECLARE @TONG MONEY, @TONGDT MONEY
EXEC CAU3_PROC '0001', '2015', @TONG OUTPUT, @TONGDT OUTPUT
PRINT N'TỔNG HD: ' + CONVERT(NVARCHAR,@TONG)
PRINT N'TỔNG DT: ' + CONVERT(NVARCHAR,@TONGDT)
GO
-- 4. Cho biết tổng số lượng đã nhập và tổng số tiền đã nhập của một mặt hàng nào đó trong một năm nào đó dựa vào mã hàng hóa nào đó
CREATE PROCEDURE CAU4_PROC
(
	@MAHH NVARCHAR(20),
	@NAM INT,
	@TONGSLNHAP INT OUTPUT,
	@TONGTIENNHAP MONEY OUTPUT
)
AS
BEGIN
	SELECT
		@TONGSLNHAP = SUM(CT_PHIEUNHAP.SL),
		@TONGTIENNHAP = SUM(CT_PHIEUNHAP.SL * CT_PHIEUNHAP.GiaMua) 
	FROM CT_PHIEUNHAP
		INNER JOIN PHIEUNHAP ON PHIEUNHAP.MaPN = CT_PHIEUNHAP.MaPN
	WHERE CT_PHIEUNHAP.MaHH = @MAHH AND YEAR(PHIEUNHAP.NgayLap) = @NAM
END
GO

-- Chạy test
DECLARE @TONG INT, @TONGNHAP MONEY
EXEC CAU4_PROC '0003', '2015', @TONG OUTPUT, @TONGNHAP OUTPUT
PRINT N'TỔNG SL NHẬP: ' + CONVERT(NVARCHAR,@TONG)
PRINT N'TỔNG TIỀN NHẬP: ' + CONVERT(NVARCHAR,@TONGNHAP)
GO
-- 5. Tính tổng số tiền thu được của từng hóa đơn
CREATE PROCEDURE CAU5_PROC
AS 
BEGIN
	SELECT
		DISTINCT CT_HOADON.MaHD,
		SUM(CT_HOADON.SL * HANGHOA.GiaBan) AS TONGTIEN
	FROM CT_HOADON
		INNER JOIN HANGHOA ON HANGHOA.MaHH = CT_HOADON.MaHH	 
	GROUP BY CT_HOADON.MaHD
END
GO

-- Chạy test
EXEC CAU5_PROC
GO
-- 6. Tính tổng số lượng và tổng số tiền đã bán được của từng hàng hóa
CREATE PROCEDURE CAU6_PROC
AS
BEGIN
	SELECT
		DISTINCT HANGHOA.MaHH,
		SUM(CT_PHIEUNHAP.SL) AS SL,
		SUM(CT_HOADON.SL * HANGHOA.GiaBan) AS TIENDABAN
	FROM CT_PHIEUNHAP
		INNER JOIN HANGHOA ON HANGHOA.MaHH = CT_PHIEUNHAP.MaHH
		INNER JOIN CT_HOADON ON CT_HOADON.MaHH = HANGHOA.MaHH
	GROUP BY HANGHOA.MaHH
END
GO

-- Chạy test
EXEC CAU6_PROC
GO
-- 7. Tính tổng số lượng và tổng số tiền đã nhập của từng hàng hóa
CREATE PROCEDURE CAU7_PROC
AS
BEGIN
	SELECT
		DISTINCT CT_PHIEUNHAP.MaHH,
		SUM(CT_PHIEUNHAP.SL) AS SL,
		SUM(CT_PHIEUNHAP.SL * CT_PHIEUNHAP.GiaMua) AS TIENDANHAP
	FROM CT_PHIEUNHAP
	GROUP BY CT_PHIEUNHAP.MaHH
END
GO

-- Chạy test
EXEC CAU7_PROC
GO
-- 8. Tính tổng số hóa đơn đã lập trong từng tháng của năm 2015
CREATE PROCEDURE CAU8_PROC
AS 
BEGIN
	SELECT 
		MONTH(HOADON.NgayLap) AS THANG,
		COUNT(DISTINCT HOADON.MaHD) AS TONGHD
	FROM 
		HOADON 
	WHERE YEAR(HOADON.NgayLap) = 2015
	GROUP BY MONTH(HOADON.NgayLap)
END
GO

-- Chạy test
EXEC CAU8_PROC
GO